### ISSUE TITLE
MultiUserApp doesn't reliably synchronize

### ISSUE THREAD

**Issue by jerlich** [GenieFramework/StippleDemos#2]
I opened the multiuser app on 3 browsers on the same machine (safari, chrome, brave). The controls on all three browsers only updated the plot on one browser (seemingly the one that was opened last).

If i close the "updating" window. the others still do not update, even with a browser refresh.

Sometimes slider changes are not noticed (even in the julia console).

I then tried 3 windows of the same browser and things worked as expected (with some missed changed). But interestingly, when i then opened a 4th window in Safari, it acted independently. The julia console reported changes in brave or safari, but only updated within browser.

**Comment by essenciary** [comment]
Thanks @jerlich - checking to see if I can reproduce. 

What is the output of: 
`julia> versioninfo()`
and 
`pkg> st`
please? 

Thanks!

**Comment by essenciary** [comment]
I can't replicate on macos - running multiple windows of Firefox and Chrome, all is synced within the same browser. Will try Safari too but momentarily my latest downgrade broke it :-/
I'll also test on windows. 

It seems to work perfectly in private (incognito) windows as well, but I expect this is due to the fact that @hhaensel used headers. I would try the session cookie approach instead, to manage "connections", and I expect this will create distinct sessions for incognito windows.

**Comment by hhaensel** [comment]
Maybe, there is some misunderstanding in the functionality of the Demo App.

It is built such that it recognises the browser type. So within each browser the windows should synchronise, but different browsers should act differently. This behaviour is achieved by
```
route("/") do
  headers = Genie.Requests.getheaders()
  user = headers["User-Agent"] |> split |> last
  ui(user)
end
```

If you are interested in seeing the header you can define
```
route("/header") do
  headers = Genie.Requests.getheaders()
end
```
Then navigate to `localhost:8000/header` and you will find the User-Agent token listed in the output. I typically ends with the browser name.
If you want a different behaviour then you need to find some other logic that identifies your computer or username.

**Comment by jerlich** [comment]
<img width="1259" alt="Screen Shot 2021-01-21 at 1 26 28 PM" src="https://user-images.githubusercontent.com/2465395/105283924-63d14280-5bec-11eb-91e4-04e873643783.png">

Here is a screenshot of an example where I have 3 windows with the same browser open (only 2 are in the screenshot). I'm moving only the sliders in the rightmost window. All the graphs update, but the UI controls do not (i haven't checked if those are also supposed to sync).

You can see that the current offset of the slider is -1.8, but the console did not detect that change. It still thinks the offset is 0.0.

```julia
(StippleDemos) pkg> st
Status `~/extrarepos/StippleDemos/Project.toml`
  [aaaa29a8] Clustering v0.14.2
  [a93c6f00] DataFrames v0.21.8
  [c43c736e] Genie v1.12.0
  [ce6b1742] RDatasets v0.6.10
  [4acbeb90] Stipple v0.6.0
  [30ddb3f0] StippleCharts v0.3.1
  [a3c5d34a] StippleUI v0.2.3
```

```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.sjtug.sjtu.edu.cn/julia

```

**Comment by hhaensel** [comment]
Very strange, indeed. Could you right-click -> inspect and see what the console output in the browser windows are?

**Comment by hhaensel** [comment]
@jerlich Is this still open? If so, please detail the status or share a screenshot of your browser's inspector.

**Comment by jerlich** [comment]
I just got a fresh clone of the repo and tried it on Julia-1.6-rc1 and I can't replicate any of the earlier problems.
