### ISSUE TITLE
checking serversidefiltering.jl is this a typo

### ISSUE THREAD

**Issue by AbhimanyuAryan** [GenieFramework/StippleDemos#21]
@hhaensel  v-bind takes `filterAbortFn`: https://github.com/GenieFramework/StippleDemos/blob/1d698a940e35d831c09e39ec94b739a947a546fb/AdvancedExamples/ServerSideFiltering.jl#L46

and in js_methods it's defined as `abortFilterFn`: https://github.com/GenieFramework/StippleDemos/blob/1d698a940e35d831c09e39ec94b739a947a546fb/AdvancedExamples/ServerSideFiltering.jl#L26

**Comment by hhaensel** [comment]
It's a typo!

**Comment by hhaensel** [comment]
Good catch!
